---
# tasks for installing OpenJDK
- name: Installing Pre-Reqs
  apt:
    name: apt-transport-https
    state: present
  become: true
  with_items:
    - apt-transport-https
    - software-properties-common

- name: Enabling deb http://http.debian.net/debian jessie-backports main
  apt_repository:
    repo: deb http://http.debian.net/debian jessie-backports main
    state: present
  become: true
  when: ansible_distribution_release == "jessie"

- name: Adding OpenJDK PPA
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
  become: true
  when: >
        ansible_distribution == "Ubuntu" and
        ansible_distribution_version|int <= 16.04
- name: debian | Installing Java
  apt:
    default_release: jessie-backports
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ openjdk_debian_packages }}"
  when: ansible_distribution_release == "jessie"

- name: Installing Java
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ openjdk_debian_packages }}"
  when: ansible_distribution_release != "jessie"

- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre'

- name: Set JAVA_PATH
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^PATH'
    line: 'PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin'

- name: install maven (and other packages if needed)
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - maven

#
# tasks for installing apache-maven
#- name: Checking if Maven is already installed
#  stat:
#    path: '{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}'
#  register: maven_installed

#- name: Downloading Maven Binaries
#  get_url:
#    url: '{{ maven_download_url }}'
#   dest: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
#    url_username: '{{ maven_download_username }}'
#    url_password: '{{ maven_download_password }}'
# when: maven_installed.stat.exists != True

#- name: Unarchive Maven Binaries
#  unarchive:
#    src: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
#   dest: '{{ maven_home_parent_directory }}'
#   copy: no
#  when: maven_installed.stat.exists != True

#- name: Remove old path configuration
# file:
#   path: /etc/profile.d/maven.sh
#   state: absent

#- name: Maven path configuration
# lineinfile:
#    dest: /etc/profile.d/maven.sh
#    line: '{{ item.line }}'
#   create: yes
#    state: present
#  with_items:
#    - { line: 'M2_HOME={{maven_home_parent_directory}}/apache-maven-{{maven_version}}' }
#    - { line: 'PATH=$PATH:$M2_HOME/bin' }

#- name: Cleaning Up
#  file:
#    state: absent
#    path: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'

# Git Clone repository Boxfuse
- name: Download Boxfuse
  git:
    repo: "{{ boxfuse_repo }}"
    version: master
    dest: "{{ playbook_dir }}/boxfuse"
    force: yes

# Maven clean package
- name: maven clean package
  command: mvn -f "{{ playbook_dir }}/boxfuse/pom.xml" clean package

# tasks for installing tomcat
- name: Create folder
  file:
    path: "{{ playbook_dir }}/tomcat"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download Tomcat
  get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz dest="{{ playbook_dir }}/tomcat"

- name: Extract archive
  unarchive: src="{{ playbook_dir }}/tomcat/apache-tomcat-8.5.9.tar.gz" dest="{{ playbook_dir }}/tomcat"

- name: start apache-tomcat
  shell: "{{ playbook_dir }}/tomcat/apache-tomcat-8.5.9/bin/startup.sh"

- name: copy boxfuse-sample-java-war-hello.war
  shell: cp "{{ playbook_dir }}/boxfuse/target/*.war" "{{ playbook_dir }}/tomcat/apache-tomcat-8.5.9/webapps/"